name: Typecheck

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: package.json

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate codes
        run: yarn run codegen

      - name: Copy config.json
        run: cp src/config/_config.json src/config/config.json

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Typecheck
        run: |
          tsc --pretty false --noEmit | \
            reviewdog -f=tsc -reporter=github-pr-check -fail-on-error=true -filter-mode="${FILTER_MODE}"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_MODE: ${{ (github.ref_name == 'master' && 'nofilter') || 'added' }}
